In [52]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [53]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [54]:
scaler.ndim

0

In [55]:
scaler.item()

7

In [56]:
vector = torch.tensor([1, 2, 3, 4])
vector

tensor([1, 2, 3, 4])

In [57]:
matrix = torch.tensor([[1, 4,3], [3, 4,3],[5, 6,3]])
matrix

tensor([[1, 4, 3],
        [3, 4, 3],
        [5, 6, 3]])

In [58]:
matrix.ndim

2

In [59]:
matrix[0]

tensor([1, 4, 3])

In [60]:
matrix.shape

torch.Size([3, 3])

In [61]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])

In [62]:
TENSOR.ndim

3

In [63]:
TENSOR.shape    

torch.Size([3, 2, 3])

In [64]:
###random tensors
random_tensor = torch.rand(3,4)
random_tensor



tensor([[0.5128, 0.1880, 0.7225, 0.4544],
        [0.8239, 0.0033, 0.0272, 0.2815],
        [0.4060, 0.5456, 0.1618, 0.2881]])

In [65]:
# create a tensor with similar shape to an image
random_image_size_tensor = torch.rand(128, 128, 3)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([128, 128, 3]), 3)

In [66]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [67]:
ones.dtype

torch.float32

creating a range of tensors and tensors like

In [68]:
torch.range(0, 10)

/var/folders/1p/cz3nhr5j78978bvwg1k_2k0c0000gn/T/ipykernel_5386/1549641488.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [69]:
oneToTen = torch.arange(start=0, end = 10, step = 2)
oneToTen



tensor([0, 2, 4, 6, 8])

In [70]:
ten_zeroes = torch.zeros_like(input=oneToTen)
ten_zeroes

tensor([0, 0, 0, 0, 0])

In [71]:
float_32_tensor = torch.tensor([1, 2, 3], dtype=None)

float_32_tensor


tensor([1, 2, 3])