In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/utils/_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(


In [3]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [6]:
vector = torch.tensor([1, 2, 3, 4])
vector

tensor([1, 2, 3, 4])

In [7]:
matrix = torch.tensor([[1, 4,3], [3, 4,3],[5, 6,3]])
matrix

tensor([[1, 4, 3],
        [3, 4, 3],
        [5, 6, 3]])

In [8]:
matrix.ndim

2

In [9]:
matrix[0]

tensor([1, 4, 3])

In [10]:
matrix.shape

torch.Size([3, 3])

In [11]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape    

torch.Size([3, 2, 3])

In [14]:
###random tensors
random_tensor = torch.rand(3,4)
random_tensor



tensor([[0.3417, 0.5715, 0.5837, 0.3144],
        [0.0441, 0.4423, 0.0545, 0.9859],
        [0.4413, 0.9552, 0.4831, 0.7398]])

In [15]:
# create a tensor with similar shape to an image
random_image_size_tensor = torch.rand(128, 128, 3)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([128, 128, 3]), 3)

In [16]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

creating a range of tensors and tensors like

In [18]:
torch.range(0, 10)

/var/folders/1p/cz3nhr5j78978bvwg1k_2k0c0000gn/T/ipykernel_8442/1549641488.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
oneToTen = torch.arange(start=0, end = 10, step = 2)
oneToTen



tensor([0, 2, 4, 6, 8])

In [20]:
ten_zeroes = torch.zeros_like(input=oneToTen)
ten_zeroes

tensor([0, 0, 0, 0, 0])

In [21]:
float_32_tensor = torch.tensor([1, 2, 3], dtype=None)

float_32_tensor


tensor([1, 2, 3])