In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/utils/_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(


In [12]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [13]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [14]:
vector = torch.tensor([1, 2, 3, 4])
vector

tensor([1, 2, 3, 4])

In [14]:
matrix = torch.tensor([[1, 4,3], [3, 4,3],[5, 6,3]])
matrix

tensor([[1, 4, 3],
        [3, 4, 3],
        [5, 6, 3]])

In [15]:
matrix.ndim

2

In [16]:
matrix[0]

tensor([1, 4, 3])

In [ ]:
matrix.shape

torch.Size([3, 3])

In [7]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])

In [8]:
TENSOR.ndim

3

In [9]:
TENSOR.shape    

torch.Size([3, 2, 3])

In [4]:
###random tensors
random_tensor = torch.rand(3,4)
random_tensor



tensor([[1.1824e-01, 6.3702e-01, 6.9333e-02, 3.9077e-04],
        [8.7302e-01, 4.4427e-02, 9.7197e-02, 9.1022e-01],
        [8.9333e-01, 3.2594e-01, 1.3581e-01, 2.4283e-01]])

In [3]:
# create a tensor with similar shape to an image
random_image_size_tensor = torch.rand(128, 128, 3)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([128, 128, 3]), 3)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])